apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-primary
  labels:
    app: my-app
    app.kubernetes.io/instance: diffapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
        app.kubernetes.io/instance: diffapp.
    spec:
      containers:
        - name: my-app
          image: reethu2/java:v8
          ports:
            - containerPort: 8082
